### ISSUE TITLE
Colors in "etterna-graph-settings.json"

### ISSUE THREAD

**Issue by KoleckOLP** [kangalioo/etterna-graph#40]
Plese allow us to change colors of the background, text and more by adding these colors to the settings.json file and changing these will change the colors of the program

We were able to do this with util.py but in the bundeled releases we can't do that.
pwease Kali. Love and emotional support Koleck.

**Comment by kangalio** [comment]
Done in 9b97b9a8848eafb09837548b95888fb51ed19844, in form of nice and pretty color picker widgets in the settings menu.
